source("tests/extensions_fixture.R")
set.seed(871)
d<-data.frame(CancerType=rep(c("A","B","C","D"),c(40,30,19,20)),CN=rnorm(109))
d$Expression<-.6*d$CN+match(d$CancerType,LETTERS)+rnorm(109)
r<-tcga_cancer_statistics(d)
stopifnot(all(r$N==c(40,30,19,20)),!r$eligible[r$CancerType=="C"],is.na(r$Pearson_P[r$CancerType=="C"]),sum(r$eligible)==3)
for(cancer in c("A","B","D")){
 a<-d[d$CancerType==cancer,];b<-r[r$CancerType==cancer,];pe<-cor.test(a$CN,a$Expression);sp<-cor.test(a$CN,a$Expression,method="spearman",exact=FALSE)
 assert_close(b$Pearson_r,pe$estimate);assert_p(b$Pearson_P,pe$p.value);assert_close(b$Spearman_rho,sp$estimate);assert_p(b$Spearman_P,sp$p.value)
 assert_close(c(b$Pearson_CI_low,b$Pearson_CI_high),tanh(atanh(pe$estimate)+c(-1,1)*qnorm(.975)/sqrt(nrow(a)-3)))
}
assert_close(r$Pearson_FDR,p.adjust(r$Pearson_P,"BH"));assert_close(r$Spearman_FDR,p.adjust(r$Spearman_P,"BH"))
fit<-lm(Expression~CN+CancerType,data=d);a<-tcga_adjusted_statistics(d)
assert_close(a$coefficients$estimate,coef(fit));assert_close(a$coefficients$p.value,summary(fit)$coefficients[,4])
z<-tcga_adjusted_statistics(d,TRUE);expected<-lm(scale(Expression)~scale(CN)+CancerType,data=d)
assert_close(z$coefficients$estimate,coef(expected));stopifnot(!tcga_adjusted_statistics(d[d$CancerType=="A",])$eligible)
constant<-d;constant$CN<-1;stopifnot(!any(tcga_cancer_statistics(constant)$eligible))
aliased<-d;aliased$CN<-match(aliased$CancerType,LETTERS);stopifnot(!tcga_adjusted_statistics(aliased)$eligible)
cat("PASS: cancer grouping, N>=20, correlations/BH, Fisher-z CI, raw/standardized adjusted regression and constant-CN skips.\n")
