Sys.setlocale("LC_CTYPE","English_United States.utf8")
print(getwd());print(R.version[c("platform","arch","os")])
path<-file.path(getwd(),"renv/library/windows/R-4.5/x86_64-w64-mingw32")
print(dir(path));print(file.exists(file.path(path,"renv/DESCRIPTION")))
.libPaths(c(path,.libPaths()));print(.libPaths());print(find.package("renv"));print(find.package("optparse"))
library(renv)
Sys.setenv(RENV_PATHS_CACHE=file.path(getwd(),".runtime/renv-cache"),RENV_PATHS_ROOT=file.path(getwd(),".runtime/renv-root"))
renv::load(project=getwd())
print(.libPaths());print(find.package("optparse"))
