invisible(Sys.setlocale("LC_CTYPE","English_United States.utf8"));source(".Rprofile")
renv::hydrate(packages=c("assertthat","DBI"),sources="D:/R/R-4.5.0/library",prompt=FALSE)
library(arrow);library(duckdb)
stopifnot(as.character(getRversion())=="4.5.0")
table<-arrow::Table$create(data.frame(value=c(1,2)))
stopifnot(nrow(as.data.frame(table))==2)
con<-DBI::dbConnect(duckdb::duckdb());stopifnot(DBI::dbGetQuery(con,"SELECT 1 AS n")$n==1);DBI::dbDisconnect(con,shutdown=TRUE)
renv::settings$snapshot.type("all")
renv::snapshot(prompt=FALSE)
renv::restore(prompt=FALSE)
status<-renv::status();stopifnot(isTRUE(status$synchronized))
writeLines(capture.output(renv::status()),"docs/RENV_STATUS.txt")
pkgs<-c("data.table","dplyr","tidyr","ggplot2","ggpubr","ggrepel","patchwork","broom","scales","stringr","purrr","readr","jsonlite","digest","optparse","future.apply","renv","arrow","duckdb")
data.table::fwrite(data.frame(package=pkgs,version=vapply(pkgs,function(p)as.character(packageVersion(p)),character(1))),"data/manifests/R_package_versions.csv")
writeLines(capture.output(sessionInfo()),"docs/R_SESSION_INFO.txt")
