Sys.setlocale("LC_CTYPE","English_United States.utf8")
stopifnot(as.character(getRversion())=="4.5.0")
source(".Rprofile")
renv::settings$snapshot.type("all")
renv::snapshot(prompt=FALSE)
renv::restore(prompt=FALSE)
status<-renv::status()
writeLines(capture.output(renv::status()),"docs/RENV_STATUS.txt")
stopifnot(isTRUE(status$synchronized))
