Sys.setlocale("LC_CTYPE", "English_United States.utf8")
stopifnot(as.character(getRversion()) == "4.5.0")
options(repos=c(CRAN="https://cloud.r-project.org"))
pkgs <- c("data.table","dplyr","tidyr","ggplot2","ggpubr","ggrepel","patchwork","broom","scales","stringr","purrr","readr","jsonlite","digest","optparse","future.apply")
available <- setNames(c(pkgs,"renv","arrow","duckdb") %in% rownames(installed.packages()),c(pkgs,"renv","arrow","duckdb"))
print(available)
bootstrap <- file.path(getwd(),".runtime/R-bootstrap")
dir.create(bootstrap,recursive=TRUE,showWarnings=FALSE)
.libPaths(c(bootstrap,.libPaths()))
if (!available[["renv"]]) install.packages("renv",lib=bootstrap,type="binary")
Sys.setenv(RENV_PATHS_CACHE=file.path(getwd(),".runtime/renv-cache"),RENV_PATHS_ROOT=file.path(getwd(),".runtime/renv-root"))
renv::init(bare=TRUE,restart=FALSE)
missing <- pkgs[!available[pkgs]]
if(length(missing)) renv::install(missing,type="binary")
present <- c(pkgs,c("arrow","duckdb")[available[c("arrow","duckdb")]])
# Copy existing R 4.5.0 packages into the project library, including dependencies.
deps <- unique(c(present,unlist(tools::package_dependencies(present,installed.packages(lib.loc="D:/R/R-4.5.0/library"),recursive=TRUE))))
ip <- installed.packages(lib.loc="D:/R/R-4.5.0/library")
deps <- intersect(deps,rownames(ip)[is.na(ip[,"Priority"])])
renv::hydrate(packages=deps,sources="D:/R/R-4.5.0/library",prompt=FALSE)
renv::snapshot(packages=unique(c(present,"renv")),prompt=FALSE)
renv::restore(prompt=FALSE)
renv::status()
versions <- data.frame(package=present,version=vapply(present,function(p)as.character(packageVersion(p)),character(1)))
write.csv(versions,"data/manifests/R_package_versions.csv",row.names=FALSE)
writeLines(capture.output(sessionInfo()),"docs/R_SESSION_INFO.txt")
